# Generated by Django 4.2.11 on 2024-03-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_slug_alter_post_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_livro',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
