# Generated by Django 4.2.11 on 2024-03-29 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_comentario_id_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='id_livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
    ]
