# Generated by Django 4.2.11 on 2024-04-06 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comentario_id_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data2',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
