# Generated by Django 4.2.11 on 2024-03-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_comentario_data2"),
    ]

    operations = [
        migrations.AddField(
            model_name="cadastro",
            name="nome_do_livro",
            field=models.CharField(max_length=100, blank=False, null=False),
        )
    ]
