# Generated by Django 4.2.11 on 2024-04-08 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_cadastro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cadastro',
            options={},
        ),
    ]
