# Generated by Django 4.2.11 on 2024-04-08 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_cadastro_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
